### ISSUE TITLE
Setup instructions?

### ISSUE THREAD

**Issue by ksmith0** [mmoran0032/NMRpy#18]
I've tried the following, but I'm not sure what happened. I am not able to find a binary called nmrfreq.

`$ python setup.py install --user`

What does this install process do? Thanks!

**Comment by mmoran0032** [comment]
You'll need to install `setuptools` for your environment, but after that, you should have the executable located in `~/.local/bin/nmrfreq`.

**Comment by ksmith0** [comment]
Thanks that clears everything up.
